version: '3.8'

services:
  rust-app:
    image: ${DOCKERHUB_USERNAME}/offline-rust-deps:0.3

    build:
      context: .
      dockerfile: Dockerfile

  rust-app-latest:
    image: ${DOCKERHUB_USERNAME}/offline-rust-deps:latest

    build:
      context: .
      dockerfile: Dockerfile
