[package]
name = "rust_lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"] # This could also be cdylib for a dynamic library

[dependencies]

[build-dependencies]
cbindgen = "0.29.2"